spring:
  application:
    name: extractor

  data:
    mongodb:
      uri: mongodb://localhost:27017/cluster

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.mongodb: WARN
    org.apache.kafka: WARN

app:
  mongodb:
    collection-name: products_v1
  kafka:
    topic-name: product-topic