name: Snyk Security Scan

on:
  workflow_dispatch:

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Auth Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test --file=build.gradle

      - name: Run Snyk Fix
        run: snyk fix --file=build.gradle -- --gradle-sub-command=./gradlew

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: automatic dependency updates from Snyk'
          title: '[Snyk] Fix security vulnerabilities'
          body: |
            ## Snyk Automated Security Fix
            
            This PR contains automatic fixes for security vulnerabilities detected by Snyk.
            
            Please review and merge if appropriate.
          branch: snyk-fix-vulnerabilities
          delete-branch: true