name: Snyk Security Scan

on:
  workflow_dispatch:

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run Snyk Test
        continue-on-error: true
        run: |
          echo "JAVA_HOME=${JAVA_HOME}"
          ./gradlew -v
          npx snyk test --severity-threshold=low
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Fix
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        with:
          command: fix
          args: -- --gradle-sub-command=./gradlew

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: automatic dependency updates from Snyk'
          title: '[Snyk] Fix security vulnerabilities'
          body: |
            ## Snyk Automated Security Fix
            
            This PR contains automatic fixes for security vulnerabilities detected by Snyk.
            
            Please review and merge if appropriate.
          branch: snyk-fix-vulnerabilities
          delete-branch: true